In [11]:
import numpy as np
import pandas as pd
import openpyxl

In [15]:
dataframe22juin = pd.read_excel("22June2020 (1).xlsx","22June2020_B")
dataframe22juin_2 = pd.read_excel("22June2020 (1).xlsx","22June2020_A")
#dataframe29juin = pd.read_excel("29June2020 (1).xlsx","29June2020_B")
#dataframe29juin_2 = pd.read_excel("29June2020 (2).xlsx","29June2020_A")

ValueError: Worksheet named '22June2020_A' not found

In [13]:
dataframe.head()

,t_stamp,P1_STATE,LIT101.Pv,FIT101.Pv,MV101.Status,P101.Status,P102.Status,P2_STATE,FIT201.Pv,AIT201.Pv,...,FIT601.Pv,P601.Status,P602.Status,P603.Status,LSH601.Alarm,LSL601.Alarm,LSH602.Alarm,LSL602.Alarm,LSH603.Alarm,LSL603.Alarm
0,2020-06-22 10:00:00.000,3,695.284100,0.0,1,1,1,2,0.000256,18.072288,...,0.000256,1,1,1,Inactive,Inactive,Active,Inactive,Inactive,Active
1,2020-06-22 10:00:01.000,3,695.127100,0.0,1,1,1,2,0.000256,18.104332,...,0.000256,1,1,1,Inactive,Inactive,Active,Inactive,Inactive,Active
2,2020-06-22 10:00:02.005,3,694.930847,0.0,1,1,1,2,0.000256,18.104332,...,0.000256,1,1,1,Inactive,Inactive,Active,Inactive,Inactive,Active
3,2020-06-22 10:00:03.010,3,694.930847,0.0,1,1,1,2,0.000256,18.104332,...,0.000256,1,1,1,Inactive,Inactive,Active,Inactive,Inactive,Active
4,2020-06-22 10:00:04.015,3,694.852300,0.0,1,1,1,2,0.000256,18.104332,...,0.000256,1,1,1,Inactive,Inactive,Active,Inactive,Inactive,Active